/**
 * Bundle a last-resort CJK webfont: subset Noto Serif SC to exactly the
 * Chinese characters (and CJK punctuation) that appear in src/i18n.ts, and
 * emit the @font-face CSS that gates it behind a unicode-range.
 *
 * The font stacks list the platform serifs (Songti SC / SimSun / Noto Serif
 * CJK SC) BEFORE this family, so devices that have any Chinese serif never
 * download it — it only kicks in on font-starved systems (minimal Linux,
 * containers) that would otherwise render tofu.
 *
 * Run `npm run subset-cjk` after adding Chinese UI strings; commit the
 * regenerated woff2 + css. The ~25 MB Noto source TTF is downloaded once and
 * cached under node_modules/.cache/.
 */
import subsetFont from 'subset-font';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const SOURCE_URL = 'https://raw.githubusercontent.com/google/fonts/main/ofl/notoserifsc/NotoSerifSC%5Bwght%5D.ttf';
const CACHE = 'node_modules/.cache/NotoSerifSC[wght].ttf';
const STRINGS = 'src/i18n.ts';
const OUT_WOFF2 = 'src/assets/fonts/NotoSerifSC.subset.woff2';
const OUT_CSS = 'src/assets/fonts/noto-serif-sc.subset.css';

// ---- collect the CJK codepoints used by the UI strings ----
// everything from the CJK blocks onward (ideographs, CJK punctuation like
// 。？、 and fullwidth forms); Latin stays with the site's Latin faces
const text = readFileSync(STRINGS, 'utf8');
const cps = [...new Set([...text].map((c) => c.codePointAt(0)).filter((cp) => cp >= 0x2e80))].sort((a, b) => a - b);
if (cps.length === 0) {
  console.error(`no CJK characters found in ${STRINGS} — nothing to subset`);
  process.exit(1);
}

// ---- fetch the source font (cached) ----
if (!existsSync(CACHE)) {
  console.log(`downloading Noto Serif SC (~25 MB, one-time, cached at ${CACHE}) ...`);
  mkdirSync('node_modules/.cache', { recursive: true });
  const res = await fetch(SOURCE_URL);
  if (!res.ok) throw new Error(`download failed: ${res.status}`);
  writeFileSync(CACHE, Buffer.from(await res.arrayBuffer()));
}

// ---- subset: pin the variable wght axis to 400, emit woff2 ----
const woff2 = await subsetFont(readFileSync(CACHE), String.fromCodePoint(...cps), {
  targetFormat: 'woff2',
  variationAxes: { wght: 400 },
});
writeFileSync(OUT_WOFF2, woff2);

// ---- emit the @font-face with a compact unicode-range ----
const ranges = [];
for (const cp of cps) {
  const last = ranges[ranges.length - 1];
  if (last && cp === last[1] + 1) last[1] = cp;
  else ranges.push([cp, cp]);
}
const hex = (cp) => cp.toString(16).toUpperCase();
const unicodeRange = ranges.map(([a, b]) => (a === b ? `U+${hex(a)}` : `U+${hex(a)}-${hex(b)}`)).join(', ');

writeFileSync(
  OUT_CSS,
  `/* GENERATED by scripts/subset-cjk.mjs — do not edit by hand.
   Last-resort CJK serif: Noto Serif SC subset to the ${cps.length} characters
   used in ${STRINGS}. The stacks in style.css list the platform CJK serifs
   first, so this only downloads on devices with no Chinese font at all. */
@font-face {
  font-family: 'Noto Serif SC Subset';
  font-style: normal;
  font-weight: 400 700;
  font-display: swap;
  src: url('./NotoSerifSC.subset.woff2') format('woff2');
  unicode-range: ${unicodeRange};
}
`,
);

console.log(`subset ${cps.length} codepoints → ${OUT_WOFF2} (${(woff2.length / 1024).toFixed(1)} KB)`);
console.log(`wrote ${OUT_CSS}`);
